server:
  port: 9201
spring:
  application:
    name: hystrix-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:9001/eureka/,http://replica2:9002/eureka/
service-url:
  user-service: http://user-service

