server:
  port: 9103
spring:
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:9001/eureka/,http://replica2:9002/eureka/ #同时注册到两个注册中心
service-url:
  user-service: http://user-service
